# Generated by Django 3.2.9 on 2021-12-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фамилия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('make', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=10, unique=True, verbose_name='Номер Машины')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver_app.driver', verbose_name='Водитель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
